describe('lualua', function()
  local lib = require('lualua')

  local function nr(k, ...)
    local n = select('#', ...)
    if k ~= n then
      error(('wrong number of return values: expected %d, got %d'):format(k, n), 2)
    end
    return ...
  end

  local function docall(s, nargs, nresults)
    return function()
      s:call(nargs, nresults)
    end
  end

  local function assertFails(msg, f, ...)
    local n = select('#', ...)
    local args = { ... }
    local function thunk()
      return f(unpack(args, 1, n))
    end
    assert.errors(thunk, msg)
  end

  describe('library', function()
    it('is a table with newstate and constants', function()
      assert.same('table', type(lib))
      assert.Nil(getmetatable(lib))
      assert.Not.Nil(lib.newstate)
      for k, v in pairs(lib) do
        assert.same('string', type(k))
        assert.same(k == 'newstate' and 'function' or k == 'iselune' and 'boolean' or 'number', type(v))
      end
    end)

    it('has some specific constants', function()
      assert.same('number', type(lib.GLOBALSINDEX))
      assert.same('number', type(lib.REGISTRYINDEX))
      assert.same('number', type(lib.TNIL))
      assert.same('nil', type(lib.nonsense))
    end)
  end)

  describe('newstate', function()
    it('creates state userdata', function()
      local s = nr(1, lib.newstate())
      assert.same('userdata', type(s))
      assert.same('lualua state', getmetatable(s))
      assert.Not.same(s, lib.newstate())
    end)
    it('starts with an empty stack', function()
      local s = nr(1, lib.newstate())
      assert.same(0, nr(1, s:gettop()))
    end)
    it('creates new states every time', function()
      local s1 = nr(1, lib.newstate())
      local s2 = nr(1, lib.newstate())
      local s3 = nr(1, lib.newstate())
      assert.Not.same(s1, s2)
      assert.Not.same(s1, s3)
      assert.Not.same(s2, s3)
    end)
  end)

  describe('state api', function()
    describe('call', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assert.errors(docall(s, 0, 0), 'stack underflow')
      end)
      it('fails on non-function', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assert.errors(docall(s, 0, 0), 'attempt to call a number value')
        assert.same(0, s:gettop())
      end)
      it('fails on function that errors', function()
        local s = lib.newstate()
        s:loadstring('unknown()')
        assert.errors(docall(s, 0, 0), 'attempt to call global \'unknown\' (a nil value)')
      end)
      it('works', function()
        local s = lib.newstate()
        s:loadstring('local a, b, c = ...; return a + 5, "foo", ...')
        s:pushnumber(42)
        s:pushboolean(false)
        nr(0, s:call(2, lib.MULTRET))
        assert.same(4, s:gettop())
        assert.same(47, s:tonumber(1))
        assert.same('foo', s:tostring(2))
        assert.same(42, s:tonumber(3))
        assert.same(false, s:toboolean(4))
      end)
    end)

    describe('checkstack', function()
      it('works with zero', function()
        local s = lib.newstate()
        assert.same(true, nr(1, s:checkstack(0)))
      end)
      it('makes room for pushing', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          s:pushnil()
        end
        assert.same(true, nr(1, s:checkstack(2)))
        s:pushnil()
        s:pushnil()
        assertFails('stack overflow', s.pushnil, s)
      end)
      it('works at limit', function()
        local s = lib.newstate()
        assert.same(true, nr(1, s:checkstack(lib.MAXCSTACK)))
      end)
      it('fails beyond limit', function()
        local s = lib.newstate()
        assert.same(false, nr(1, s:checkstack(lib.MAXCSTACK + 1)))
      end)
      it('works with nonempty stack', function()
        local s = lib.newstate()
        s:pushnil()
        s:pushnil()
        assert.same(true, nr(1, s:checkstack(lib.MAXCSTACK - 2)))
        assert.same(false, nr(1, s:checkstack(lib.MAXCSTACK - 1)))
      end)
      it('negative numbers are ignored', function()
        local s = lib.newstate()
        assert.same(true, nr(1, s:checkstack(-100)))
        assert.same(true, nr(1, s:checkstack(-lib.MAXCSTACK * 2)))
      end)
    end)

    describe('concat', function()
      it('works with zero', function()
        local s = lib.newstate()
        nr(0, s:concat(0))
        assert.same(1, s:gettop())
        assert.same('', s:tostring(1))
      end)
      it('works', function()
        local s = lib.newstate()
        s:pushstring('foo')
        s:pushstring('bar')
        s:pushstring('baz')
        s:pushstring('quux')
        nr(0, s:concat(3))
        assert.same(2, s:gettop())
        assert.same('foo', s:tostring(1))
        assert.same('barbazquux', s:tostring(2))
      end)
      it('fails on tables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        assertFails('attempt to concatenate a table value', s.concat, s, 2)
      end)
      it('fails past the end', function()
        local s = lib.newstate()
        assertFails('stack underflow', s.concat, s, 42)
      end)
      it('does nothing with negative values', function()
        local s = lib.newstate()
        s:pushstring('moo')
        s:pushstring('cow')
        nr(0, s:concat(-2))
        assert.same(2, s:gettop())
        assert.same('moo', s:tostring(1))
        assert.same('cow', s:tostring(2))
        nr(0, s:concat(-200))
        assert.same(2, s:gettop())
        assert.same('moo', s:tostring(1))
        assert.same('cow', s:tostring(2))
      end)
    end)

    describe('equal', function()
      it('works with numbers', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        s:pushnumber(42)
        assert.same(true, nr(1, s:equal(1, 3)))
        assert.same(false, nr(1, s:equal(2, 3)))
      end)
      it('works with strings', function()
        local s = lib.newstate()
        s:pushstring('foo')
        s:pushstring('bar')
        s:pushstring('foo')
        assert.same(true, nr(1, s:equal(1, 3)))
        assert.same(false, nr(1, s:equal(2, 3)))
      end)
      it('works with tables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushvalue(1)
        assert.same(true, nr(1, s:equal(1, 3)))
        assert.same(false, nr(1, s:equal(2, 3)))
      end)
      it('honors metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('__eq')
        s:pushlfunction(function(ss)
          ss:pushboolean(true)
          return 1
        end)
        s:settable(-3)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        assert.same(true, nr(1, s:equal(-1, -2)))
      end)
    end)

    describe('error', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('stack underflow', s.error, s)
      end)
      it('works outside pushlfunction, by failing', function()
        local s = lib.newstate()
        s:pushstring('womp womp')
        assertFails('womp womp', s.error, s)
      end)
      it('works in pushlfunction', function()
        local s = lib.newstate()
        s:pushlfunction(function(ss)
          ss:pushstring('womp womp')
          ss:error()
        end)
        assert.errors(docall(s, 0, 0), 'womp womp')
        assert.same(0, s:gettop())
      end)
    end)

    describe('getfenv', function()
      it('fails on invalid index', function()
        local s = lib.newstate()
        assertFails('invalid index', s.getfenv, s, 0)
        assert.same(0, s:gettop())
      end)
      it('works', function()
        local s = lib.newstate()
        s:loadstring('return')
        nr(0, s:getfenv(-1))
        assert.same(2, s:gettop())
        assert.same(true, s:isfunction(1))
        assert.same(true, s:istable(2))
        assert.same(true, s:equal(-1, lib.GLOBALSINDEX))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:loadstring('return')
        for _ = 2, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.getfenv, s, 1)
      end)
    end)

    describe('getfield', function()
      it('fails on invalid index', function()
        local s = lib.newstate()
        assertFails('invalid index', s.getfield, s, 0, 'foo')
        assert.same(0, s:gettop())
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('attempt to index a number value', s.getfield, s, 1, 'foo')
      end)
      it('pushes nil on missing field', function()
        local s = lib.newstate()
        s:newtable()
        nr(0, s:getfield(-1, 'foo'))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
      end)
      it('pushes value on present field', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('foo')
        s:pushstring('bar')
        s:settable(-3)
        nr(0, s:getfield(-1, 'foo'))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same('bar', s:tostring(2))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:newtable()
        for _ = 2, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.getfield, s, 1, 'foo')
      end)
    end)

    describe('getglobal', function()
      it('requires a string argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (string expected, got no value)', s.getglobal, s)
      end)
      it('works', function()
        local s = lib.newstate()
        nr(0, s:getglobal('foo'))
        assert.same(1, s:gettop())
        assert.same(true, s:isnil(1))
        s:pop(1)
        s:pushnumber(42)
        s:setfield(lib.GLOBALSINDEX, 'foo')
        assert.same(0, s:gettop())
        nr(0, s:getglobal('foo'))
        assert.same(1, s:gettop())
        assert.same(42, s:tonumber(1))
      end)
    end)

    describe('getmetatable', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.getmetatable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('returns false on numbers', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assert.same(false, nr(1, s:getmetatable(-1)))
      end)
      it('returns false on tables without a metatable', function()
        local s = lib.newstate()
        s:newtable()
        assert.same(false, nr(1, s:getmetatable(-1)))
      end)
      it('works on userdata', function()
        local s = lib.newstate()
        s:newuserdata()
        s:newtable()
        s:setmetatable(-2)
        assert.same(true, nr(1, s:getmetatable(-1)))
      end)
      it('success on almost full stack', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:setmetatable(1)
        for _ = 2, lib.MINSTACK - 1 do
          s:pushnil()
        end
        assert.same(true, nr(1, s:getmetatable(1)))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:setmetatable(1)
        for _ = 2, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.getmetatable, s, 1)
      end)
    end)

    describe('gettable', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.gettable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('works getting itself', function()
        local s = lib.newstate()
        s:newtable()
        nr(0, s:gettable(-1))
        assert.same(1, s:gettop())
        assert.same(true, s:isnil(1))
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('attempt to index a number value', s.gettable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('honors metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushstring('__index')
        s:pushlfunction(function(ss)
          ss:pushvalue(2)
          ss:pushstring('cow')
          ss:concat(2)
          return 1
        end)
        s:settable(-3)
        s:setmetatable(-2)
        s:pushstring('moo')
        nr(0, s:gettable(-2))
        assert.same('moocow', s:tostring(-1))
      end)
    end)

    describe('gettop', function()
      it('starts at zero', function()
        local s = lib.newstate()
        assert.same(0, nr(1, s:gettop()))
      end)
      it('tracks settop', function()
        local s = lib.newstate()
        s:settop(15)
        assert.same(15, nr(1, s:gettop()))
      end)
    end)

    describe('insert', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.insert, s, -1)
      end)
      it('is a no-op at -1', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('foo')
        nr(0, s:insert(-1))
        assert.same(2, s:gettop())
        assert.same(42, s:tonumber(1))
        assert.same('foo', s:tostring(2))
      end)
      it('is a swap at -2', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('foo')
        s:pushboolean(true)
        nr(0, s:insert(-2))
        assert.same(3, s:gettop())
        assert.same(42, s:tonumber(1))
        assert.same(true, s:toboolean(2))
        assert.same('foo', s:tostring(3))
      end)
      it('works on full stack', function()
        local s = lib.newstate()
        for i = 1, lib.MINSTACK do
          s:pushnumber(i)
        end
        nr(0, s:insert(1))
        assert.same(lib.MINSTACK, s:tonumber(1))
        for i = 2, lib.MINSTACK do
          assert.same(i - 1, s:tonumber(i))
        end
      end)
      it('fails on globals pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.insert, s, lib.GLOBALSINDEX)
      end)
      it('fails on registry pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.insert, s, lib.REGISTRYINDEX)
      end)
      it('fails on environment pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.insert, s, lib.ENVIRONINDEX)
      end)
      if lib.iselune then
        it('fails on error handler pseudo-index', function()
          local s = lib.newstate()
          s:pushnumber(42)
          assertFails('invalid index', s.insert, s, lib.ERRORHANDLERINDEX)
        end)
      end
    end)

    describe('isnil', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnil()
        assert.same(false, nr(1, s:isnil(1)))
        assert.same(true, nr(1, s:isnil(2)))
      end)
    end)

    describe('isnumber', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('99')
        s:pushstring('wat')
        s:pushnil()
        assert.same(true, nr(1, s:isnumber(1)))
        assert.same(true, nr(1, s:isnumber(2)))
        assert.same(false, nr(1, s:isnumber(3)))
        assert.same(false, nr(1, s:isnumber(4)))
      end)
    end)

    describe('isstring', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('99')
        s:pushstring('wat')
        s:pushnil()
        assert.same(true, nr(1, s:isstring(1)))
        assert.same(true, nr(1, s:isstring(2)))
        assert.same(true, nr(1, s:isstring(3)))
        assert.same(false, nr(1, s:isstring(4)))
      end)
    end)

    describe('istable', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('wat')
        s:newtable()
        s:pushnil()
        assert.same(false, nr(1, s:istable(1)))
        assert.same(false, nr(1, s:istable(2)))
        assert.same(true, nr(1, s:istable(3)))
        assert.same(false, nr(1, s:istable(4)))
      end)
    end)

    describe('lessthan', function()
      it('works with numbers', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        assert.same(false, nr(1, s:lessthan(1, 1)))
        assert.same(true, nr(1, s:lessthan(1, 2)))
        assert.same(false, nr(1, s:lessthan(2, 1)))
      end)
      it('works with strings', function()
        local s = lib.newstate()
        s:pushstring('bar')
        s:pushstring('foo')
        assert.same(false, nr(1, s:lessthan(1, 1)))
        assert.same(true, nr(1, s:lessthan(1, 2)))
        assert.same(false, nr(1, s:lessthan(2, 1)))
      end)
      it('fails with tables', function()
        local s = lib.newstate()
        s:newtable()
        assertFails('attempt to compare two table values', s.lessthan, s, 1, 1)
      end)
      it('honors metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('__lt')
        s:pushlfunction(function(ss)
          ss:pushboolean(true)
          return 1
        end)
        s:settable(-3)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        assert.same(true, nr(1, s:lessthan(-1, -2)))
      end)
    end)

    describe('loadstring', function()
      it('requires an argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (string expected, got no value)', s.loadstring, s)
      end)
      it('pushes a function and returns zero on success', function()
        local s = lib.newstate()
        assert.same(0, nr(1, s:loadstring('return 42')))
        assert.same(1, s:gettop())
        assert.same(true, s:isfunction(1))
      end)
      it('pushes an error message and returns ERRSYNTAX on parse failure', function()
        local s = lib.newstate()
        assert.same(lib.ERRSYNTAX, nr(1, s:loadstring('not a valid lua function body')))
        assert.same(1, s:gettop())
        assert.same(true, s:isstring(1))
      end)
      it('success with MAXSTACK-1 returns', function()
        local s = lib.newstate()
        local t = {}
        for i = 1, lib.MAXSTACK - 1 do
          table.insert(t, i)
        end
        assert.same(0, nr(1, s:loadstring('return ' .. table.concat(t, ','))))
      end)
      it('failure with MAXSTACK returns', function()
        local s = lib.newstate()
        local t = {}
        for i = 1, lib.MAXSTACK do
          table.insert(t, i)
        end
        assert.same(lib.ERRSYNTAX, nr(1, s:loadstring('return ' .. table.concat(t, ','))))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.loadstring, s, 'return 42')
        assert.same(0, s:gettop())
      end)
    end)

    describe('newtable', function()
      it('works', function()
        local s = lib.newstate()
        nr(0, s:newtable())
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        nr(0, s:newtable())
        assert.same(2, s:gettop())
        assert.same(true, s:istable(2))
        assert.same(false, s:equal(1, 2))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          nr(0, s:newtable())
        end
        assertFails('stack overflow', s.newtable, s)
      end)
    end)

    describe('newuserdata', function()
      it('works', function()
        local s = lib.newstate()
        local t = nr(1, s:newuserdata())
        assert.same('table', type(t))
        assert.Nil(getmetatable(t))
        assert.same(1, s:gettop())
        assert.same(true, s:isuserdata(1))
        assert.equal(t, s:touserdata(1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.newuserdata, s)
      end)
    end)

    describe('next', function()
      it('fails on invalid index', function()
        local s = lib.newstate()
        assertFails('bad argument #1 (table expected, got no value)', s.next, s, 1)
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('foo')
        s:pushstring('bar')
        s:settable(-3)
        s:pushnil()
        assert.same(true, nr(1, s:next(1)))
        assert.same(3, s:gettop())
        assert.same('foo', s:tostring(2))
        assert.same('bar', s:tostring(3))
        s:pop(1)
        assert.same(false, nr(1, s:next(1)))
        assert.same(1, s:gettop())
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:newtable()
        for _ = 2, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.next, s, 1)
      end)
    end)

    describe('objlen', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.objlen, s, -1)
      end)
      it('returns string length', function()
        local s = lib.newstate()
        s:pushstring('hello world')
        assert.same(11, nr(1, s:objlen(-1)))
      end)
      it('returns length of number string', function()
        local s = lib.newstate()
        s:pushnumber(12345)
        assert.same(5, nr(1, s:objlen(-1)))
      end)
      it('returns zero on empty tables', function()
        local s = lib.newstate()
        s:newtable()
        assert.same(0, nr(1, s:objlen(-1)))
      end)
      it('returns array length', function()
        local s = lib.newstate()
        s:newtable()
        for i = 1, 36 do
          s:pushstring('moo')
          s:rawseti(-2, i)
        end
        assert.same(36, nr(1, s:objlen(-1)))
      end)
      -- TODO test userdata, should probably be zero but is currently sizeof(int*)
    end)

    describe('pcall', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('stack underflow', s.pcall, s, 0, 0, 0)
      end)
      it('returns ERRRUN on non-function', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, 0)))
      end)
      it('returns ERRRUN on function that errors', function()
        local s = lib.newstate()
        s:loadstring('unknown()')
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, 0)))
        assert.same(1, s:gettop())
        assert.same(true, s:isstring(1))
      end)
      it('works', function()
        local s = lib.newstate()
        s:loadstring('local a, b, c = ...; return a + 5, "foo", ...')
        s:pushnumber(42)
        s:pushboolean(false)
        assert.same(0, nr(1, s:pcall(2, lib.MULTRET, 0)))
        assert.same(4, s:gettop())
        assert.same(47, s:tonumber(1))
        assert.same('foo', s:tostring(2))
        assert.same(42, s:tonumber(3))
        assert.same(false, s:toboolean(4))
      end)
      it('fails on invalid errfunc index', function()
        local s = lib.newstate()
        s:loadstring('unknown()')
        assertFails('invalid index', s.pcall, s, 0, 0, -2)
        assert.same(0, s:gettop())
      end)
      it('returns ERRERR on erroring function that is also its errfunc', function()
        local s = lib.newstate()
        assert.same(0, s:loadstring('unknown()'))
        assert.same(lib.ERRERR, nr(1, s:pcall(0, 0, -1)))
        assert.same(1, s:gettop())
        assert.same('errfunc error', s:tostring(1))
      end)
      it('returns ERRERR if errfunc is not a function', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assert.same(0, s:loadstring('unknown()'))
        assert.same(lib.ERRERR, nr(1, s:pcall(0, 0, -2)))
        assert.same(2, s:gettop())
        assert.same(42, s:tonumber(1))
        assert.same('errfunc error', s:tostring(2))
      end)
      it('properly invokes errfunc, only preserves first result', function()
        local s = lib.newstate()
        assert.same(0, s:loadstring('local x = ...; return "moo: " .. x, 42'))
        assert.same(0, s:loadstring('unknown()'))
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, -2)))
        assert.same(2, s:gettop())
        assert.same(true, s:isfunction(1))
        assert.same('string', s:typename(2))
        assert.same('moo: ', s:tostring(2):sub(1, 5))
      end)
      it('works with lfunctions that panic the host', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushlfunction(function(ss)
          ss:pushnumber(99)
          error('doh')
        end)
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, 0)))
        assert.same(2, s:gettop())
        assert.Not.Nil(s:tostring(-1):find('doh'))
      end)
      it('works with lfunctions that explicitly panic the sandbox', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushlfunction(function(ss)
          ss:pushstring('doh')
          ss:error()
        end)
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, 0)))
        assert.same(2, s:gettop())
        assert.Not.Nil(s:tostring(-1):find('doh'))
      end)
      it('works with lfunctions that implicitly panic the sandbox', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushlfunction(function(ss)
          ss:pushstring('doh')
          ss:getfield(-1, 'hello')
        end)
        assert.same(lib.ERRRUN, nr(1, s:pcall(0, 0, 0)))
        assert.same(2, s:gettop())
        assert.same('attempt to index a string value', s:tostring(-1))
      end)
    end)

    describe('pop', function()
      it('fails without an argument', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('bad argument #2 to \'f\' (number expected, got no value)', s.pop, s)
      end)
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(43)
        s:pushnumber(44)
        nr(0, s:pop(2))
        assert.same(1, s:gettop())
        assert.same(42, s:tonumber(-1))
      end)
      it('works with zero', function()
        local s = lib.newstate()
        nr(0, s:pop(0))
      end)
      it('works going to empty', function()
        local s = lib.newstate()
        s:pushnumber(42)
        nr(0, s:pop(1))
        assert.same(0, s:gettop())
      end)
      it('fails when popping beyond end', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('stack underflow', s.pop, s, 2)
        assert.same(0, s:gettop())
      end)
      it('negatives confined to stack size', function()
        local s = lib.newstate()
        nr(0, s:pop(-1))
        nr(0, s:pop(-lib.MINSTACK))
        assertFails('stack underflow', s.pop, s, -lib.MINSTACK - 1)
      end)
    end)

    describe('pushboolean', function()
      it('no argument is false', function()
        local s = lib.newstate()
        nr(0, s:pushboolean())
        assert.same(false, s:toboolean(-1))
      end)
      it('works with true', function()
        local s = lib.newstate()
        nr(0, s:pushboolean(true))
        assert.same(true, s:toboolean(-1))
      end)
      it('works with false', function()
        local s = lib.newstate()
        nr(0, s:pushboolean(false))
        assert.same(false, s:toboolean(-1))
      end)
      it('nil is false', function()
        local s = lib.newstate()
        nr(0, s:pushboolean(nil))
        assert.same(false, s:toboolean(-1))
      end)
      it('nonzero is true', function()
        local s = lib.newstate()
        nr(0, s:pushboolean(1))
        assert.same(true, s:toboolean(-1))
      end)
      it('zero is true', function()
        local s = lib.newstate()
        nr(0, s:pushboolean(0))
        assert.same(true, s:toboolean(-1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          nr(0, s:pushboolean(true))
        end
        assertFails('stack overflow', s.pushboolean, s, true)
      end)
    end)

    describe('pushlfunction', function()
      it('works', function()
        local s = lib.newstate()
        s:pushlfunction(function(ss)
          assert.same(2, ss:gettop())
          assert.same(42, ss:tonumber(1))
          assert.same('foo', ss:tostring(2))
          ss:pushstring('bar')
          ss:pushnumber(99)
          ss:pushnil()
          return 3
        end)
        s:pushnumber(42)
        s:pushstring('foo')
        s:call(2, lib.MULTRET)
        assert.same(3, s:gettop())
        assert.same('bar', s:tostring(1))
        assert.same(99, s:tonumber(2))
        assert.same(true, s:isnil(3))
      end)
      it('works with extra args', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushlfunction(function() end, 42)
        s:call(0, 0)
        assert.same(1, s:gettop())
      end)
      it('fails gracefully', function()
        local s = lib.newstate()
        s:pushlfunction(function()
          _G.missingfunction()
        end)
        assert.errors(docall(s, 0, 0), 'attempt to call field \'missingfunction\' (a nil value)')
        assert.same(0, s:gettop())
      end)
      it('works from loadstring', function()
        local s = lib.newstate()
        s:pushlfunction(function(ss)
          ss:pushstring('womp womp')
          ss:error()
        end)
        s:setfield(lib.GLOBALSINDEX, 'moocow')
        s:loadstring('moocow()')
        assert.errors(docall(s, 0, 0), 'womp womp')
      end)
    end)

    describe('pushnil', function()
      it('works', function()
        local s = lib.newstate()
        nr(0, s:pushnil())
        assert.same(1, s:gettop())
        assert.same(true, s:isnil(1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          nr(0, s:pushnil())
        end
        assertFails('stack overflow', s.pushnil, s)
      end)
    end)

    describe('pushnumber', function()
      it('requires an argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (number expected, got no value)', s.pushnumber, s)
      end)
      it('works', function()
        local s = lib.newstate()
        nr(0, s:pushnumber(42))
        assert.same(42, s:tonumber(-1))
      end)
      it('works on number string', function()
        local s = lib.newstate()
        nr(0, s:pushnumber('42'))
        assert.same(42, s:tonumber(-1))
      end)
      it('fails on non-number string', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (number expected, got string)', s.pushnumber, s, 'wat')
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          nr(0, s:pushnumber(42))
        end
        assertFails('stack overflow', s.pushnumber, s, 42)
      end)
    end)

    describe('pushstring', function()
      it('requires an argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (string expected, got no value)', s.pushstring, s)
      end)
      it('works', function()
        local s = lib.newstate()
        nr(0, s:pushstring('wat'))
        assert.same('wat', s:tostring(-1))
      end)
      it('works with numbers', function()
        local s = lib.newstate()
        nr(0, s:pushstring(42))
        assert.same('42', s:tostring(-1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        for _ = 1, lib.MINSTACK do
          nr(0, s:pushstring('foo'))
        end
        assertFails('stack overflow', s.pushstring, s, 'foo')
      end)
    end)

    describe('pushvalue', function()
      it('requires an argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (number expected, got no value)', s.pushvalue, s)
      end)
      it('works with strings', function()
        local s = lib.newstate()
        s:pushstring('wat')
        nr(0, s:pushvalue(-1))
        assert.same(2, s:gettop())
        assert.same('wat', s:tostring(-1))
      end)
      it('works with nil', function()
        local s = lib.newstate()
        s:pushnil()
        nr(0, s:pushvalue(-1))
        assert.same(2, s:gettop())
        assert.same(true, s:isnil(-1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:pushnil()
        for _ = 2, lib.MINSTACK do
          nr(0, s:pushvalue(-1))
        end
        assertFails('stack overflow', s.pushvalue, s, -1)
      end)
    end)

    describe('rawequal', function()
      it('works with numbers', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        s:pushnumber(42)
        assert.same(true, nr(1, s:rawequal(1, 3)))
        assert.same(false, nr(1, s:rawequal(2, 3)))
      end)
      it('works with strings', function()
        local s = lib.newstate()
        s:pushstring('foo')
        s:pushstring('bar')
        s:pushstring('foo')
        assert.same(true, nr(1, s:rawequal(1, 3)))
        assert.same(false, nr(1, s:rawequal(2, 3)))
      end)
      it('works with tables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushvalue(1)
        assert.same(true, nr(1, s:rawequal(1, 3)))
        assert.same(false, nr(1, s:rawequal(2, 3)))
      end)
      it('ignores metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('__eq')
        s:pushlfunction(function(ss)
          ss:pushboolean(true)
          return 1
        end)
        s:settable(-3)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        s:newuserdata()
        s:pushvalue(1)
        s:setmetatable(-2)
        assert.same(false, nr(1, s:rawequal(-1, -2)))
      end)
    end)

    describe('rawget', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.rawget, s, -1)
        assert.same(0, s:gettop())
      end)
      it('works getting itself', function()
        local s = lib.newstate()
        s:newtable()
        nr(0, s:rawget(-1))
        assert.same(1, s:gettop())
        assert.same(true, s:isnil(1))
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('bad argument #-1 (table expected, got number)', s.rawget, s, -1)
        assert.same(0, s:gettop())
      end)
      it('ignores metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushstring('__index')
        s:pushlfunction(function(ss)
          ss:pushvalue(2)
          ss:pushstring('cow')
          ss:concat(2)
          return 1
        end)
        s:settable(-3)
        s:setmetatable(-2)
        s:pushstring('moo')
        nr(0, s:rawget(-2))
        assert.same(true, s:isnil(-1))
      end)
    end)

    describe('rawgeti', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.rawgeti, s, -1, 42)
      end)
      it('fails on numbers', function()
        local s = lib.newstate()
        s:pushnumber(12345)
        assertFails('bad argument #-1 (table expected, got number)', s.rawgeti, s, -1, 42) -- TODO fix
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnumber(42)
        s:pushstring('foo')
        s:settable(-3)
        nr(0, s:rawgeti(-1, 42))
        assert.same('foo', s:tostring(-1))
        nr(0, s:rawgeti(-2, 99))
        assert.same(true, s:isnil(-1))
      end)
      it('fails on full stack', function()
        local s = lib.newstate()
        s:newtable()
        for _ = 2, lib.MINSTACK do
          s:pushnil()
        end
        assertFails('stack overflow', s.rawgeti, s, 1, 42)
      end)
    end)

    describe('rawset', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.rawset, s, -1)
        assert.same(0, s:gettop())
      end)
      it('fails just setting itself', function()
        local s = lib.newstate()
        s:newtable()
        assertFails('stack underflow', s.rawset, s, -1)
        assert.same(0, s:gettop())
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        assertFails('bad argument #-2 (table expected, got number)', s.rawset, s, -2)
        assert.same(0, s:gettop())
      end)
      it('works in simple case', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('foo')
        s:pushstring('bar')
        nr(0, s:rawset(-3))
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        s:pushstring('foo')
        s:gettable(-2)
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same('bar', s:tostring(2))
      end)
      it('table can be its own key', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnil()
        s:pushvalue(-2)
        s:pushstring('bar')
        nr(0, s:rawset(-2))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        s:pushvalue(-2)
        s:gettable(-3)
        assert.same(3, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        assert.same('bar', s:tostring(3))
      end)
      it('table can be its own value', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnil()
        s:pushstring('foo')
        s:pushvalue(-3)
        nr(0, s:rawset(-1))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        s:pushstring('foo')
        s:gettable(-3)
        assert.same(3, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        assert.same(true, s:equal(1, 3))
      end)
      it('ignores metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushstring('__newindex')
        s:pushlfunction(function(ss)
          ss:pushstring('bark')
          ss:concat(2)
          ss:rawset(-3)
          return 1
        end)
        s:settable(-3)
        s:setmetatable(-2)
        s:pushstring('moo')
        s:pushstring('cow')
        nr(0, s:rawset(-3))
        s:getfield(-1, 'moo')
        assert.same('cow', s:tostring(-1))
      end)
    end)

    describe('rawseti', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.rawseti, s, -1, 42)
      end)
      it('fails on numbers', function()
        local s = lib.newstate()
        s:pushnumber(12345)
        assertFails('bad argument #-1 (table expected, got number)', s.rawseti, s, -1, 42) -- TODO fix
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('foo')
        nr(0, s:rawseti(-2, 42))
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        s:pushnumber(42)
        s:gettable(-2)
        assert.same('foo', s:tostring(2))
      end)
    end)

    describe('ref', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('stack underflow', s.ref, s, lib.REGISTRYINDEX)
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring(99)
        assertFails('bad argument #-2 (table expected, got number)', s.ref, s, -2) -- TODO fix
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:pushvalue(-1)
        local ref = s:ref(lib.REGISTRYINDEX)
        assert.same('number', type(ref))
        s:rawgeti(lib.REGISTRYINDEX, ref)
        assert.same(true, s:equal(-1, -2))
      end)
    end)

    describe('remove', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.remove, s, -1)
      end)
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('foo')
        nr(0, s:remove(-2))
        assert.same(1, s:gettop())
        assert.same('foo', s:tostring(1))
      end)
      it('fails on globals pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.remove, s, lib.GLOBALSINDEX)
      end)
      it('fails on registry pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.remove, s, lib.REGISTRYINDEX)
      end)
      it('fails on environment pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.remove, s, lib.ENVIRONINDEX)
      end)
      if lib.iselune then
        it('fails on error handler pseudo-index', function()
          local s = lib.newstate()
          s:pushnumber(42)
          assertFails('invalid index', s.remove, s, lib.ERRORHANDLERINDEX)
        end)
      end
    end)

    describe('replace', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.replace, s, -1)
      end)
      it('works', function()
        local s = lib.newstate()
        s:pushboolean(true)
        s:pushnumber(42)
        s:pushstring('foo')
        nr(0, s:replace(-3))
        assert.same(2, s:gettop())
        assert.same('foo', s:tostring(1))
        assert.same(42, s:tonumber(2))
      end)
      it('fails on globals pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.replace, s, lib.GLOBALSINDEX)
      end)
      it('fails on registry pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.replace, s, lib.REGISTRYINDEX)
      end)
      it('fails on environment pseudo-index', function()
        local s = lib.newstate()
        s:pushnumber(42)
        assertFails('invalid index', s.replace, s, lib.ENVIRONINDEX)
      end)
      if lib.iselune then
        it('fails on error handler pseudo-index', function()
          local s = lib.newstate()
          s:pushnumber(42)
          assertFails('invalid index', s.replace, s, lib.ERRORHANDLERINDEX)
        end)
      end
    end)

    describe('setfield', function()
      it('fails on invalid index', function()
        local s = lib.newstate()
        assertFails('invalid index', s.setfield, s, 0, 'foo')
        assert.same(0, s:gettop())
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        assertFails('attempt to index a number value', s.setfield, s, 1, 'foo')
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnumber(99)
        nr(0, s:setfield(-2, 'foo'))
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        s:pushstring('foo')
        s:gettable(-2)
        assert.same(99, s:tonumber(2))
      end)
      it('can set table as value and pops table', function()
        local s = lib.newstate()
        s:newtable()
        s:pushvalue(-1)
        nr(0, s:setfield(-2, 'foo'))
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        s:pushstring('foo')
        s:gettable(-2)
        assert.same(true, s:equal(1, 2))
      end)
      it('succeeds on full stack', function()
        local s = lib.newstate()
        s:newtable()
        for _ = 2, lib.MINSTACK - 1 do
          s:pushnil()
        end
        s:pushnumber(99)
        nr(0, s:setfield(1, 'foo'))
        assert.same(lib.MINSTACK - 1, s:gettop())
      end)
    end)

    describe('setglobal', function()
      it('requires a string argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (string expected, got no value)', s.setglobal, s)
      end)
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('stack underflow', s.setglobal, s, 'foo')
      end)
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        nr(0, s:setglobal('foo'))
        assert.same(0, s:gettop())
        s:getfield(lib.GLOBALSINDEX, 'foo')
        assert.same(1, s:gettop())
        assert.same(42, s:tonumber(1))
      end)
    end)

    describe('setmetatable', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.setmetatable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('fails if metatable is a number', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnumber(42)
        assertFails('type error', s.setmetatable, s, -2)
        assert.same(0, s:gettop())
      end)
      it('works', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushstring('__metatable')
        s:pushstring('hi there i am a metatable')
        s:settable(-3)
        assert.same(true, nr(1, s:setmetatable(-2)))
        assert.same(1, s:gettop())
        assert.same(true, s:getmetatable(-1))
        s:pushstring('__metatable')
        s:gettable(-2)
        assert.same('hi there i am a metatable', s:tostring(-1))
      end)
      it('works if metatable is nil', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnil()
        assert.same(true, nr(1, s:setmetatable(-2)))
      end)
      it('works on userdata', function()
        local s = lib.newstate()
        s:newuserdata()
        s:newtable()
        s:pushvalue(-1)
        assert.same(true, nr(1, s:setmetatable(-3)))
        assert.same(true, s:getmetatable(-2))
        assert.same(true, s:equal(-1, -2))
      end)
      it('works on numbers', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnumber(42)
        s:pushvalue(-2)
        assert.same(true, nr(1, s:setmetatable(-2)))
        s:pop(1)
        s:pushnumber(99)
        assert.same(true, s:getmetatable(-1))
        assert.same(true, s:equal(1, 3))
      end)
      it('can set a table\'s metatable to itself, and also pops it', function()
        local s = lib.newstate()
        s:newtable()
        s:pushvalue(-1)
        assert.same(true, nr(1, s:setmetatable(-1)))
        assert.same(1, s:gettop())
        assert.same(true, s:getmetatable(-1))
        assert.same(true, s:equal(1, 2))
      end)
      it('success on full stack', function()
        local s = lib.newstate()
        s:newtable()
        for _ = 2, lib.MINSTACK - 1 do
          s:pushnil()
        end
        s:newtable()
        assert.same(true, nr(1, s:setmetatable(1)))
      end)
    end)

    describe('settable', function()
      it('fails on empty stack', function()
        local s = lib.newstate()
        assertFails('invalid index', s.settable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('fails just setting itself', function()
        local s = lib.newstate()
        s:newtable()
        assertFails('stack underflow', s.settable, s, -1)
        assert.same(0, s:gettop())
      end)
      it('fails on non-table', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushnumber(99)
        assertFails('attempt to index a number value', s.settable, s, -2)
        assert.same(0, s:gettop())
      end)
      it('works in simple case', function()
        local s = lib.newstate()
        s:newtable()
        s:pushstring('foo')
        s:pushstring('bar')
        nr(0, s:settable(-3))
        assert.same(1, s:gettop())
        assert.same(true, s:istable(1))
        s:pushstring('foo')
        s:gettable(-2)
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same('bar', s:tostring(2))
      end)
      it('table can be its own key', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnil()
        s:pushvalue(-2)
        s:pushstring('bar')
        nr(0, s:settable(-2))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        s:pushvalue(-2)
        s:gettable(-3)
        assert.same(3, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        assert.same('bar', s:tostring(3))
      end)
      it('table can be its own value', function()
        local s = lib.newstate()
        s:newtable()
        s:pushnil()
        s:pushstring('foo')
        s:pushvalue(-3)
        nr(0, s:settable(-1))
        assert.same(2, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        s:pushstring('foo')
        s:gettable(-3)
        assert.same(3, s:gettop())
        assert.same(true, s:istable(1))
        assert.same(true, s:isnil(2))
        assert.same(true, s:equal(1, 3))
      end)
      it('honors metatables', function()
        local s = lib.newstate()
        s:newtable()
        s:newtable()
        s:pushstring('__newindex')
        s:pushlfunction(function(ss)
          ss:pushstring('bark')
          ss:concat(2)
          ss:rawset(-3)
          return 1
        end)
        s:settable(-3)
        s:setmetatable(-2)
        s:pushstring('moo')
        s:pushstring('cow')
        nr(0, s:settable(-3))
        s:getfield(-1, 'moo')
        assert.same('cowbark', s:tostring(-1))
      end)
    end)

    describe('settop', function()
      it('fails without an argument', function()
        local s = lib.newstate()
        assertFails('bad argument #2 to \'f\' (number expected, got no value)', s.settop, s)
      end)
      it('fills with nil', function()
        local s = lib.newstate()
        nr(0, s:settop(3))
        assert.same(true, s:isnil(1))
        assert.same(true, s:isnil(2))
        assert.same(true, s:isnil(3))
      end)
      it('keeps existing values on stack', function()
        local s = lib.newstate()
        s:pushnumber(3)
        s:pushnumber(4)
        s:pushnumber(5)
        s:pushnumber(6)
        nr(0, s:settop(2))
        assert.same(2, s:gettop())
        assert.same(4, s:tonumber(-1))
        assert.same(3, s:tonumber(-2))
      end)
      it('works with negative numbers', function()
        local s = lib.newstate()
        s:pushnumber(12)
        s:pushnumber(13)
        s:pushnumber(14)
        s:pushnumber(15)
        s:pushnumber(16)
        nr(0, s:settop(-4))
        assert.same(2, s:gettop())
        assert.same(13, s:tonumber(-1))
        assert.same(12, s:tonumber(-2))
      end)
      it('succeeds on 0', function()
        local s = lib.newstate()
        nr(0, s:settop(0))
        assert.same(0, s:gettop())
      end)
      it('does not fail on -1 even on empty stack', function()
        local s = lib.newstate()
        nr(0, s:settop(-1))
        assert.same(0, s:gettop())
      end)
      it('fails on negatives past the end', function()
        local s = lib.newstate()
        assertFails('invalid settop index', s.settop, s, -2)
      end)
      it('succeeds up to end of allocation', function()
        local s = lib.newstate()
        nr(0, s:settop(lib.MINSTACK))
        assert.same(lib.MINSTACK, s:gettop())
      end)
      it('fails past end of allocation', function()
        local s = lib.newstate()
        assertFails('invalid settop index', s.settop, s, lib.MINSTACK + 1)
        assert.same(0, s:gettop())
      end)
    end)

    describe('toboolean', function()
      it('works', function()
        local s = lib.newstate()
        s:pushstring('abc')
        s:pushnumber(42)
        s:pushnumber(0)
        s:pushnil()
        s:pushboolean(true)
        s:pushboolean(false)
        assert.same(true, nr(1, s:toboolean(1)))
        assert.same(true, nr(1, s:toboolean(2)))
        assert.same(true, nr(1, s:toboolean(3)))
        assert.same(false, nr(1, s:toboolean(4)))
        assert.same(true, nr(1, s:toboolean(5)))
        assert.same(false, nr(1, s:toboolean(6)))
      end)
    end)

    describe('tonumber', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('42')
        s:pushstring('wat')
        s:pushboolean(true)
        s:pushnil()
        assert.same(42, nr(1, s:tonumber(1)))
        assert.same(42, nr(1, s:tonumber(2)))
        assert.same(0, nr(1, s:tonumber(3)))
        assert.same(0, nr(1, s:tonumber(4)))
        assert.same(0, nr(1, s:tonumber(5)))
      end)
    end)

    describe('tostring', function()
      it('works', function()
        local s = lib.newstate()
        s:pushnumber(42)
        s:pushstring('42')
        s:pushstring('wat')
        s:pushboolean(true)
        s:pushnil()
        assert.same('42', nr(1, s:tostring(1)))
        assert.same('42', nr(1, s:tostring(2)))
        assert.same('wat', nr(1, s:tostring(3)))
        assert.same(nil, nr(1, s:tostring(4)))
        assert.same(nil, nr(1, s:tostring(5)))
      end)
    end)
  end)
end)
